### ISSUE TITLE
OSError: Can't load config

### ISSUE THREAD

**Issue by CANDYsj** [Eleanor-H/DAGN#1]
Hello! Thanks for sharing the source code. When I run the "run_dagn.sh" some error appeared. 
Traceback (most recent call last):
  File "/home/jsj201-1/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 353, in get_config_dict
    raise EnvironmentError
OSError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run_multiple_choice.py", line 462, in <module>
    main()
  File "run_multiple_choice.py", line 237, in main
    cache_dir=model_args.cache_dir,
  File "/home/jsj201-1/.local/lib/python3.6/site-packages/transformers/configuration_auto.py", line 272, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/jsj201-1/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 362, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for '/data2/yinyahuang/BERT_MODELS/roberta-large-uncased'. Make sure that:
- '/data2/yinyahuang/BERT_MODELS/roberta-large-uncased' is a correct model identifier listed on 'https://huggingface.co/models'
- or '/data2/yinyahuang/BERT_MODELS/roberta-large-uncased' is the correct path to a directory containing a config.json file

I guess if the path "export ROOT_DIR=/data2/yinyahuang" is wrong which doesn't appeare in the project.
I would appreciate it if you could sort this out.

**Comment by ozyyshr** [comment]
@CANDYsj You can ignore this command and alter the MODEL_DIR into "export MODEL_DIR=roberta-large", the pretrained model will be automatically downloaded.

**Comment by Eleanor-H** [comment]
Hi! Thank you for the interest in our work! 

I have updated the scripts. They now will automatically download the pre-trained model. 

Or you can download the pre-trained model [here](https://huggingface.co/models?filter=roberta) and assign the directory path to "MODEL_DIR".
